// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCffKAPwbDOxqkeZTtR27QXS2hfl6-Gw5U',
    appId: '1:747172991521:web:615ef0607aeb21184dc960',
    messagingSenderId: '747172991521',
    projectId: 'nft-app-5e17e',
    authDomain: 'nft-app-5e17e.firebaseapp.com',
    storageBucket: 'nft-app-5e17e.appspot.com',
    measurementId: 'G-Y5NB6CDTEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwrHzAqHkaazl9cRkz6QQXPDC-CeP0fDk',
    appId: '1:747172991521:android:0653813807fd311e4dc960',
    messagingSenderId: '747172991521',
    projectId: 'nft-app-5e17e',
    storageBucket: 'nft-app-5e17e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEbYbEI6Q2n-pSYqivl3XHzOF_CrVtlM0',
    appId: '1:747172991521:ios:c8c2e5860cc9d2de4dc960',
    messagingSenderId: '747172991521',
    projectId: 'nft-app-5e17e',
    storageBucket: 'nft-app-5e17e.appspot.com',
    iosBundleId: 'com.example.nftapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEbYbEI6Q2n-pSYqivl3XHzOF_CrVtlM0',
    appId: '1:747172991521:ios:c8c2e5860cc9d2de4dc960',
    messagingSenderId: '747172991521',
    projectId: 'nft-app-5e17e',
    storageBucket: 'nft-app-5e17e.appspot.com',
    iosBundleId: 'com.example.nftapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCffKAPwbDOxqkeZTtR27QXS2hfl6-Gw5U',
    appId: '1:747172991521:web:8ce9606799606d1f4dc960',
    messagingSenderId: '747172991521',
    projectId: 'nft-app-5e17e',
    authDomain: 'nft-app-5e17e.firebaseapp.com',
    storageBucket: 'nft-app-5e17e.appspot.com',
    measurementId: 'G-L5L53MC1SE',
  );
}
